### ISSUE TITLE
How to set vmoptions?

### ISSUE THREAD

**Issue by Sewdn** [itnode/docker-pdfreactor#2]
Hi,

We're looking to increase the available memory for the VM that is run within the docker container. (default is 1Gb: -Mxm1024m)

How to configure docker to set the vmoptions to increase memory?

Is it possible to set them by an environment variable, using the docker-compose.yml:
environment:
JAVA_OPTIONS: "-Xmx4096m"

This doesn't seem to be working.

In the start.sh script we see logic for setting/overriding vmoptions. How to instruct the Docker script with these overrides?

Thanks!

**Comment by jegade** [comment]
Please asked the authors of pdfreactor itself, there is a newer version

* https://hub.docker.com/r/realobjects/pdfreactor/
* http://www.pdfreactor.com/product/doc_html/index.html#ServerParameters
